-- ==========================================
-- PRIVATE QUIZ DATABASE SETUP
-- Supabase SQL Editor → paste all → Run
-- ==========================================

create table if not exists public.responses (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 1 and 60),
  answers jsonb not null,
  submitted_at timestamptz not null default now()
);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade
);

alter table public.responses enable row level security;
alter table public.admin_users enable row level security;

-- Participants can submit a response, but they cannot read responses.
drop policy if exists "public can submit quiz" on public.responses;
create policy "public can submit quiz"
on public.responses
for insert
to anon, authenticated
with check (true);

-- Only listed admin accounts can read all responses.
drop policy if exists "admins can read responses" on public.responses;
create policy "admins can read responses"
on public.responses
for select
to authenticated
using (
  exists (
    select 1
    from public.admin_users a
    where a.user_id = auth.uid()
  )
);

-- Admins can read their own admin row.
drop policy if exists "admins can read admin record" on public.admin_users;
create policy "admins can read admin record"
on public.admin_users
for select
to authenticated
using (user_id = auth.uid());

-- No public read/insert/update/delete policy exists for admin_users.
-- IMPORTANT: do not create an anon SELECT policy on responses.

-- After creating your admin account in Supabase Authentication,
-- run this with your actual auth user's UUID:
--
-- insert into public.admin_users (user_id)
-- values ('YOUR-AUTH-USER-UUID-HERE');
--
-- You can find the UUID in Authentication → Users.
